name: smart_crop_advisory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # ✅ Added localization support
    sdk: flutter
  image_picker: ^1.1.2
  provider: ^6.0.5
  http: ^1.1.0
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0
  record: ^6.1.1         # microphone recording
  audioplayers: ^6.5.1   # play TTS files
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  sqflite: ^2.3.0        # local database
  path: ^1.8.3           # path utilities
  dio: ^5.4.0            # HTTP client
  image: ^4.1.3          # image processing
  gpt_markdown: ^1.1.4  # markdown rendering


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/models/
